server:
  port: 8066


#服务的名称
spring:
  application:
    name: gateway-service

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8065/eureka/

#/order-service/api/v1/order/save?user_id=2&product_id=1
#自定义路由映射
zuul:
  routes:
    food-service: /foodService/**
    order-service: /orderService/**
    user-service: /userService/**
  #统一入口为上面的配置，其他入口忽略
#  ignored-patterns: /*-service/**

