
#数据库配置
spring:
  datasource:
    username: root
    password: scauzns
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  # freemarker相关配置, 可省略
#  freemarker:
#    suffix: .ftl
#    charset: UTF-8
#    enabled: true
#    template-loader-path: classpath:/templates/

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # 打印sql，线上环境要关闭
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8064

task:
  corePoolSize: 5
  maxPoolSize: 25
  qCapacity: 10
